LoftShop/src/LoftShopFramework/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LoftShopFramework.Data;

namespace LoftShopFramework.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            var pManager = new ProductsManager();
            var products = pManager.GetProducts(new List<Guid>() { Guid.Empty });
            return View("ProductsView");
        }

        public IActionResult ShowCategory(string catName)
        {
            var pManager = new ProductsManager();
            var cManager = new CategoriesManager();

            var categoryId = cManager.GetCategoryByName(catName);
            var products = pManager.GetProducts(new List<Guid>() { categoryId });
            return View("ProductsView");
        }
    }
}

LoftShop/src/LoftShopFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LoftShop40</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LoftShop40</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Главная</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">О нас</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Контакты</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>

    @await Html.PartialAsync("_MenuPartial")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - LoftShop40</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

LoftShop/src/LoftShopFramework/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using LoftShopFramework.Data
@using LoftShopFramework.Models.ShopViewModels
@using System.Text

@inject CategoriesManager CategoriesManager
@model IEnumerable<CategoryViewModel>

@{
    var categories = CategoriesManager.GetCategories();

    @*<li class="dropdown">
            <a asp-controller="Shop" asp-action="Index">Все категории</a>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">v</a>

            <ul class="dropdown-menu">
                @foreach (var category in categories) {
                    <li>
                        @Html.ActionLink(@category.Name, "ShowCategory", "Shop", new { name = @category.Name })
                    </li>
                }
            </ul>
        </li>*@

    <div id="mySidenav" class="sidenav">
        <div class="sidenav-container">
            <ul>
                <li>
                    @Html.ActionLink(@CategoriesManager.SummaryName, "Index", "Shop")
                </li>

                @foreach (var category in categories)
                {
                    <li>
                        @Html.ActionLink(@category.Name, "ShowCategory", "Shop", new { catName = @category.Name })
                    </li>
                }
            </ul>
        </div>
    </div>
}

<script>
    var positionSideMenu = function () {
        var sidenav = $('.sidenav');
        var topnav = $('.navbar');
        if (sidenav && topnav) {
            sidenav.css({ top: topnav.height() });
        }

        var content = $('.body-content');
        if (sidenav && content) {
            content.css({ "margin-left": sidenav.width() + 35 });
        }
    };

    window.onresize = positionSideMenu;
    window.addEventListener('load', positionSideMenu);
</script>