WorkTests/TestBalance/TestBalance/Models/BalanceEditModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TestBalance.Models
{
    public class BalanceEditModel
    {
        [DisplayName("Сумма")]
        [Required(ErrorMessage = "Сумма должна быть указана")]
        [RegularExpression(@"\d{1,27}(,\d{1,2})?")]
        public decimal Sum { get; set; }

        [DisplayName("Валюта")]
        [Required(ErrorMessage = "Валюта должна быть указана")]
        public int CurrencyId { get; set; }

        public IEnumerable<CurrencyModel> CurrencyList { get; set; }
    }
}

WorkTests/TestBalance/TestBalance/Models/BalanceModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TestBalance.Domain;

namespace TestBalance.Models
{
    public class BalanceModel
    {
        public decimal Sum { get; set; }

        public string Name { get; set; }
    }
}

WorkTests/TestBalance/TestBalance/Models/CurrencyEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TestBalance.Domain;

namespace TestBalance.Models
{
    public class CurrencyEditModel
    {
        public int Id { get; set; }
        [DisplayName("Название")]
        [Required(ErrorMessage = "Название должно быть указано")]
        public string Name { get; set; }
        public bool IsSystem { get; set; }
    }
}

WorkTests/TestBalance/TestBalance/Models/CurrencyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestBalance.Domain;

namespace TestBalance.Models
{
    public class CurrencyModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

WorkTests/TestBalance/TestBalance/Models/HistoryModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TestBalance.Domain;

namespace TestBalance.Models
{
    public class HistoryModel
    {
        public DateTime CreateDate { get; set; }
        public string CurrencyName { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public decimal BeforeSum { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public decimal AfterSum { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public decimal Delta { get; set; }
        public string UserInfo { get; set; }
    }
}

WorkTests/TestBalance/TestBalance/Controllers/BalanceController.cs
using log4net;
using System;
using System.Collections.Generic;
using System.Net;
using System.Reflection;
using System.Threading;
using System.Web.Mvc;
using TestBalance.Models;
using TestBalance.Services;

namespace TestBalance.Controllers
{
    public class BalanceController : BaseController
    {
        const string SubmitAdd = "Начислить";
        const string SubmitSubtract = "Списать";

        readonly ILog logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        readonly BalanceService balanceService = new BalanceService();

        public ActionResult Balance()
        {
            return View();
        }

        public ActionResult BalanceView()
        {
            var model = balanceService.GetBalances();
            return PartialView(model);
        }

        public ActionResult BalanceEdit()
        {
            var model = new BalanceEditModel() { CurrencyList = balanceService.GetCurrencyList() };
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult BalanceEdit(BalanceEditModel model, string submit)
        {
            //чтобы продемонстрировать прогресс бар
            Thread.Sleep(150);

            model.Sum = Math.Round(model.Sum, 2);
            if (model.Sum <= 0)
                ModelState.AddModelError(nameof(model.Sum), "Сумма должна быть больше 0.");

            if (!ModelState.IsValid)
            {
                model.CurrencyList = balanceService.GetCurrencyList();
                return PartialView(model);
            }

            try
            {
                var сallerIp = Request.ServerVariables["REMOTE_ADDR"];
                var callerAgent = Request.UserAgent;

                switch (submit)
                {
                    case SubmitAdd:
                        balanceService.UpdateBalanceSum(model.CurrencyId, model.Sum, сallerIp, callerAgent);
                        break;
                    case SubmitSubtract:
                        balanceService.UpdateBalanceSum(model.CurrencyId, -model.Sum, сallerIp, callerAgent);
                        break;
                    default:
                        throw new ArgumentException(nameof(submit));
                }

            } catch (Exception ex)
            {
                logger.Error(ex);
                ModelState.AddModelError("general", $"Произошла ошибка: {ex.Message}");
                model.CurrencyList = balanceService.GetCurrencyList();
                return PartialView(model);
            }

            return RedirectToAction(nameof(BalanceEdit));
        }
    }
}

WorkTests/TestBalance/TestBalance/Controllers/BaseController.cs
using log4net;
using System;
using System.Collections.Generic;
using System.Net;
using System.Reflection;
using System.Threading;
using System.Web.Mvc;
using TestBalance.Models;
using TestBalance.Services;

namespace TestBalance.Controllers
{
    public class BaseController : Controller
    {
        readonly ILog logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);

        protected override void OnException(ExceptionContext filterContext)
        {
            Exception ex = filterContext.Exception;
            filterContext.ExceptionHandled = false;

            logger.Error(ex);
        }
    }
}

WorkTests/TestBalance/TestBalance/Controllers/CurrencyController.cs
using log4net;
using System;
using System.Collections.Generic;
using System.Net;
using System.Reflection;
using System.Web.Mvc;
using TestBalance.Models;
using TestBalance.Services;

namespace TestBalance.Controllers
{
    public class CurrencyController : BaseController
    {
        readonly ILog logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        readonly CurrencyService сurrencyService = new CurrencyService();

        public ActionResult Currency()
        {
            return View();
        }

        public ActionResult CurrencyView()
        {
            var model = сurrencyService.GetCurrencyEditList();
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult CurrencyDelete(int? id)
        {
            сurrencyService.DeleteCurrency(id.Value);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public ActionResult CurrencyAdd()
        {
            return PartialView(new CurrencyEditModel());
        }

        [HttpPost]
        public ActionResult CurrencyAdd(CurrencyEditModel model)
        {
            var nameDuplicate = сurrencyService.HasCurrency(model.Name);
            if (nameDuplicate)
                ModelState.AddModelError(nameof(model.Name), "Валюта с таким именем уже есть.");

            if (!ModelState.IsValid)
            {
                return PartialView(model);
            }

            try
            {
                сurrencyService.AddCurrency(model);
            } catch (Exception ex)
            {
                logger.Error(ex);
                ModelState.AddModelError("general", $"Произошла ошибка: {ex.Message}");
                return PartialView(model);
            }

            return RedirectToAction(nameof(CurrencyAdd));
        }
    }
}

WorkTests/TestBalance/TestBalance/Controllers/HistoryController.cs
using log4net;
using System;
using System.Collections.Generic;
using System.Net;
using System.Reflection;
using System.Web.Mvc;
using TestBalance.Models;
using TestBalance.Services;

namespace TestBalance.Controllers
{
    public class HistoryController : BaseController
    {
        readonly HistoryService historyService = new HistoryService();

        public ActionResult History()
        {
            var model = historyService.GetHistory();
            return View(model);
        }
    }
}

WorkTests/TestBalance/TestBalance/Views/History/History.cshtml
@model IEnumerable<TestBalance.Models.HistoryModel>

@{
    ViewBag.Title = "Операции";
}

<div class="row">
    <div class="col-md-8">
        <h3>
            История операций
        </h3>
        <table class="table">
            <tr>
                <th>Дата</th>
                <th>Валюта</th>
                <th>Начальная сумма</th>
                <th>Изменение</th>
                <th>Итоговая сумма</th>
                <th>Пользователь</th>
            </tr>

            @Html.DisplayFor(t => t)
        </table>
    </div>
</div>

WorkTests/TestBalance/TestBalance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/inputmask")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Балансы", "Balance", "Balance")</li>
                    <li>@Html.ActionLink("История", "History", "History")</li>
                    <li>@Html.ActionLink("Валюты", "Currency", "Currency")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:\.\d{3})+)?(?:,\d+)?$/.test(value);
            }
        });
    </script>
</body>
</html>